# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"

  # Maintain dependencies for pub
  - package-ecosystem: "pub"
    directory: "packages/google_fonts"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pub"
    directory: "packages/dynamic_color"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
  # Unmaintained / unreleased
  # - package-ecosystem: "pub"
  #   directory: "packages/symbols"
  #   schedule:
  #     interval: "monthly"
  # - package-ecosystem: "pub"
  #   directory: "packages/adaptive_breakpoints"
  #   schedule:
  #     interval: "monthly"
  # - package-ecosystem: "pub"
  #   directory: "packages/adaptive_navigation"
  #   schedule:
  #     interval: "monthly"
  # - package-ecosystem: "pub"
  #   directory: "packages/adaptive_components"
  #   schedule:
  #     interval: "monthly"
