name: google_fonts
description: A package to include fonts from fonts.google.com in your Flutter app.
version: 2.0.0-nullsafety.0
homepage: https://github.com/material-foundation/google-fonts-flutter/
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ^1.17.0

dependencies:
  # The dependencies `http` and `crypto` are migrated to NNBD, but not
  # published yet.
  # Once the NNBD versions for these packages are published on pub.dev,
  # we need to update the dependencies.

  flutter:
    sdk: flutter
  http:
    git:
      url: https://github.com/dart-lang/http.git
      ref: 86fdb20b37c368a77ec861f825ca5eb9e21b4c6d
  path_provider: ^1.4.0
  crypto:
    git:
      url: https://github.com/dart-lang/crypto.git
      ref: 415e4f5dce0fbe2fb5381c64898db3ae0bffc143
  pedantic: ">=1.10.0-nullsafety.3 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  mustache: ^1.1.1
  protobuf: ^1.0.1
  console: ^3.1.0
