name: google_fonts
description: EXPERIMENTAL. A package to include fonts from fonts.google.com.
version: 0.1.0
homepage: https://github.com/material-components/material-components-flutter-experimental/tree/master/google_fonts

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  path_provider: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  mustache: ^1.1.1
