name: adaptive_navigation
description: A Flutter package providing adaptive switching between various navigation components.
version: 0.0.10
repository: https://github.com/material-foundation/flutter-packages/tree/main/packages/adaptive_navigation
issue_tracker: https://github.com/material-foundation/flutter-packages/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+adaptive_navigation%22
screenshots:
 - description: "Diagram of a large-screen layout labeling 3 elements of its anatomy."
   path: screenshots/layout.png
 - description: "Example app showing adaptive navigation."
   path: screenshots/example.png

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_breakpoints: ^0.1.2

dev_dependencies:
  cider: ">=0.1.3 <0.3.0"
  flutter_lints: ">=2.0.1 <4.0.0"
  flutter_test:
    sdk: flutter
