name: dynamic_color
description: Flutter plugin to obtain dynamic colors on Android.
version: 0.1.0
repository: https://github.com/material-foundation/material-dynamic-color-flutter
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  # TODO: use pub.dev when published
  material_color_utilities:
    path: ../material-color-utilities/dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  meta: ^1.3.0

flutter:
  plugin:
    platforms:
      android:
        package: io.material.plugins.dynamic_color
        pluginClass: DynamicColorPlugin
