name: dynamic_color
description: A Flutter package to create Material color schemes based on a platform's implementation of dynamic color.
version: 1.6.0
repository: https://github.com/material-foundation/material-dynamic-color-flutter

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=3.4.0-17.0.pre"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  material_color_utilities: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  meta: ^1.3.0

flutter:
  plugin:
    platforms:
      android:
        package: io.material.plugins.dynamic_color
        pluginClass: DynamicColorPlugin
      linux:
        package: io.material.plugins.dynamic_color
        pluginClass: DynamicColorPlugin
      macos:
        package: io.material.plugins.dynamic_color
        pluginClass: DynamicColorPlugin
      windows:
        package: io.material.plugins.dynamic_color
        pluginClass: DynamicColorPluginCApi
