name: adaptive_components
description: A Flutter package to implement responsive layouts in Material Design.
version: 0.0.6
repository: https://github.com/material-components/material-components-flutter-adaptive/tree/develop/adaptive_components

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_breakpoints: ^0.1.3
  adaptive_navigation: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
