name: adaptive_components
description: A Flutter package to implement responsive layouts in Material Design.
version: 0.0.10
repository: https://github.com/material-foundation/flutter-packages/tree/main/packages/adaptive_components
issue_tracker: https://github.com/material-foundation/flutter-packages/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+adaptive_components%22
screenshots:
 - description: "Diagram of row and column layouts."
   path: screenshots/row_column.png
 - description: "Example app showing adaptive components."
   path: screenshots/example.png

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_breakpoints: ^0.1.3
  adaptive_navigation: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.1 <4.0.0"
  cider: ">=0.1.3 <0.3.0"
