name: dynamic_color
description: A Flutter package to create Material color schemes based on a platform's implementation of dynamic color.
version: 1.6.2
repository: https://github.com/material-foundation/flutter-packages/tree/main/packages/dynamic_color
issue_tracker: https://github.com/material-foundation/flutter-packages/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+dynamic_color%22
screenshots:
 - description: "Key colors are extracted from a user's wallpaper."
   path: screenshots/wallpaper_extraction.png
 - description: 'A complete dynamic color scheme consists of user-generated colors and custom colors.'
   path: screenshots/full_color_scheme.png
 - description: 'Harmonization shifts tones of custom colors to ensure that visual balance and accessible contrast is achieved when combined with user-generated colors.'
   path: screenshots/harmonization.gif

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=3.4.0-17.0.pre"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  material_color_utilities: ^0.2.0

dev_dependencies:
  cider: ^0.1.3
  flutter_lints: ^2.0.0
  meta: ^1.3.0

flutter:
  plugin:
    platforms:
      android:
        package: io.material.plugins.dynamic_color
        pluginClass: DynamicColorPlugin
      linux:
        package: io.material.plugins.dynamic_color
        pluginClass: DynamicColorPlugin
      macos:
        package: io.material.plugins.dynamic_color
        pluginClass: DynamicColorPlugin
      windows:
        package: io.material.plugins.dynamic_color
        pluginClass: DynamicColorPluginCApi
