# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ubuntu-flutter-install-cache-stable

      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable
      - run: flutter doctor -v

      - uses: actions/checkout@v2
        with:
          path: "repos/dynamic_colors"

      # TODO: Remove when public
      - uses: actions/checkout@v2
        with:
          repository: material-foundation/dynamic-color-tools
          token: ${{ secrets.TEMP_PAT }}
          path: "repos/dynamic-color-tools"

      - name: Install dependencies
        run: flutter pub get
        working-directory: "repos/dynamic_colors"

      - name: Verify formatting
        run: flutter format --dry-run --set-exit-if-changed .
        working-directory: "repos/dynamic_colors"

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze
        working-directory: "repos/dynamic_colors"

      - name: Run tests
        run: flutter test
        working-directory: "repos/dynamic_colors"
