name: Update fonts
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch: # Enable manual run from Github
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
      - name: Clone Flutter repository with beta channel
        uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          channel: beta
      - run: flutter doctor -v
      - run: flutter pub get

      - run: dart pub global activate cider
      - run: dart generator/generator.dart

      - name: Read families_diff file
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6.4.0
        id: get_families_diff
        with:
          script: |
            const fs = require('fs');
            return fs.readFileSync('generator/families_diff','utf8').toString();
          result-encoding: string

      - name: Cancel workflow if there is no diff
        uses: andymckay/cancel-action@8f8510d9dea52fcc8eb6ca10d6ce47fd5fc43cd8 # 0.2
        if: steps.get_families_diff.outputs.result == ''

      - name: If cancelling workflow, allow for enough time to do so
        run: sleep 15s
        shell: bash
        if: steps.get_families_diff.outputs.result == ''

      - uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672 # v3.14.0
        with:
          token: ${{ secrets.MATERIAL_ROBOT_TOKEN }}
          committer: material-robot <featherless+materialrobot@google.com>
          commit-message: |
            [automated] update fonts

            ${{ steps.get_families_diff.outputs.result }}
          base: main
          branch: create-pull-request/update
          delete-branch: true
          author: material-robot <featherless+materialrobot@google.com>
          title: Update fonts
          body: |
            # Summary
            ${{ steps.get_families_diff.outputs.result }}

            Please note that all existing fonts are subject to being updated.
          team-reviewers: flutter-package-maintainers
          labels: automated
